### ISSUE TITLE
Error when running `mix cov`

### ISSUE THREAD

**Issue by stefanahman** [mrinalwadhwa/excov#1]
Elixir version: 1.7.3

Test config:

```
config :excov,
  :reporters, [
    ExCov.Reporter.Console
  ]

config :excov, ExCov.Reporter.Console,
  show_summary: true,
  show_detail: false
```

Console output:
```
± mix cov
Compiling 9 files (.ex)
Generated test app
....................................................................................................................

Finished in 18.5 seconds
1 doctest, 115 tests, 0 failures

Randomized with seed 389262
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:not_cover_compiled, RequestError}. This protocol is implemented for: Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version, Version.Requirement
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    (excov) lib/excov/module.ex:145: ExCov.Module.call_counts/1
    (excov) lib/excov/module.ex:63: ExCov.Module.analyse/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (excov) lib/excov/project.ex:74: ExCov.Project.analyse/1
    (excov) lib/excov.ex:65: ExCov.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

**Comment by stefanahman** [comment]
Closed due to inactivity
